//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInternship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementSpeciality
    {
        public string AgreementID { get; set; }
        public string SpecialityID { get; set; }
        public Nullable<System.DateTime> DateOfAdding { get; set; }
    
        public virtual Agreements Agreements { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
