//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInternship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreements()
        {
            this.AgreementSpeciality = new HashSet<AgreementSpeciality>();
            this.PracticeDistributions = new HashSet<PracticeDistributions>();
        }
    
        public string AgreementNumber { get; set; }
        public int AgreementType { get; set; }
        public Nullable<System.DateTime> DateOfAgreement { get; set; }
        public string CompanyName { get; set; }
        public string CompanyINN { get; set; }
        public string CompanyLegalAddress { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> AgreementStartDate { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public bool Prolongation { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public string Remark { get; set; }
        public bool IsRegistrationRequired { get; set; }
    
        public virtual AgreementTypes AgreementTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgreementSpeciality> AgreementSpeciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeDistributions> PracticeDistributions { get; set; }
    }
}
