//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInternship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeSchedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticeSchedules()
        {
            this.PracticeDistributions = new HashSet<PracticeDistributions>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public System.DateTime PracticeStartDate { get; set; }
        public System.DateTime PracticeEndDate { get; set; }
        public int PracticeSubject { get; set; }
    
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeDistributions> PracticeDistributions { get; set; }
        public virtual PracticeSubjects PracticeSubjects { get; set; }
    }
}
