//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInternship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeDistributions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticeDistributions()
        {
            this.StudentsDistribution = new HashSet<StudentsDistribution>();
        }
    
        public int ID { get; set; }
        public int PracticeScheduleID { get; set; }
        public string AgreementID { get; set; }
        public bool IsInTheSameCompany { get; set; }
    
        public virtual Agreements Agreements { get; set; }
        public virtual PracticeSchedules PracticeSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsDistribution> StudentsDistribution { get; set; }
    }
}
