//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInternship.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsIntershipDBEntities : DbContext
    {
        public StudentsIntershipDBEntities()
            : base("name=StudentsIntershipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreements> Agreements { get; set; }
        public virtual DbSet<AgreementSpeciality> AgreementSpeciality { get; set; }
        public virtual DbSet<AgreementTypes> AgreementTypes { get; set; }
        public virtual DbSet<EducationalOrganisations> EducationalOrganisations { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<PracticeDistributions> PracticeDistributions { get; set; }
        public virtual DbSet<PracticeSchedules> PracticeSchedules { get; set; }
        public virtual DbSet<PracticeSubjects> PracticeSubjects { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudentsDistribution> StudentsDistribution { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
